# Generated by Django 2.0.7 on 2018-11-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0001_initial'),
        ('vpmotask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='ScrumboardTaskList',
        ),
    ]
