# Generated by Django 2.0.7 on 2018-07-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(default='Project Name - Default', max_length=50, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateField(null=True)),
            ],
            options={
                'ordering': ('projectname',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions')),
            },
        ),
    ]
