# Generated by Django 2.0.7 on 2018-08-20 11:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(default='N/A', max_length=240)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('index', models.IntegerField(default=0)),
                ('projectname', models.CharField(default='Project Name - Default', max_length=50, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateField(null=True)),
            ],
            options={
                'ordering': ('projectname',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('user_linked', models.BooleanField(default=False)),
                ('userTeam', models.CharField(max_length=151, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions')),
            },
        ),
    ]
