# Generated by Django 2.0.7 on 2018-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0002_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user_linked',
            field=models.BooleanField(default=False),
        ),
    ]
