# Generated by Django 2.0.7 on 2018-07-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0002_auto_20180723_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
    ]
