# Generated by Django 2.0.7 on 2018-07-24 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('vpmoapp', '0003_auto_20180327_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('projectname',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='projectname',
            field=models.CharField(default='Project Name - Default', max_length=50, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
