# Generated by Django 2.0.7 on 2018-08-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0003_deliverable_parent_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='parent_team',
            new_name='parent_topic',
        ),
    ]
