# Generated by Django 2.0.7 on 2018-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('vpmoapp', '0003_auto_20180723_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
    ]
