# Generated by Django 2.0.7 on 2018-08-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0003_team_user_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='userTeam',
            field=models.CharField(default=2, max_length=151, unique=True),
            preserve_default=False,
        ),
    ]
