# Generated by Django 2.0.7 on 2018-08-19 10:59

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0006_auto_20180819_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='3c47a127f71668c0a47fd1bd', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmoapp.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='NULL', max_length=4048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmoapp.Team'),
        ),
    ]
