# Generated by Django 2.0.7 on 2018-08-20 05:51

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoapp', '0007_auto_20180819_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('name', models.CharField(default='N/A', max_length=240)),
                ('due_date', models.DateTimeField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmoapp.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
