# Generated by Django 2.0.7 on 2018-12-02 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmodoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_task', to='vpmotask.Task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_task_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
