# Generated by Django 2.0.7 on 2018-11-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048, null=True)),
                ('index', models.IntegerField(default=0)),
                ('node_type', models.CharField(default='Team', max_length=48)),
                ('channel_sid', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('severity', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('start', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('user_linked', models.BooleanField(default=False)),
                ('user_team', models.CharField(max_length=251, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('vpmotree.treestructure',),
        ),
    ]
