# Generated by Django 2.0.7 on 2018-10-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048, null=True)),
                ('index', models.IntegerField(default=0)),
                ('node_type', models.CharField(default='Team', max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('start', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions')),
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('user_linked', models.BooleanField(default=False)),
                ('user_team', models.CharField(max_length=251, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions')),
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.AddField(
            model_name='message',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpmotree.TreeStructure'),
        ),
    ]
