# Generated by Django 2.0.7 on 2018-08-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_linked', models.BooleanField(default=False)),
                ('user_team', models.CharField(max_length=151, unique=True)),
            ],
            options={
                'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions')),
            },
        ),
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nodetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vpmotree.NodeType')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpmotree.TreeStructure'),
        ),
        migrations.AddField(
            model_name='project',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpmotree.TreeStructure'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmotree.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vpmotree.Team'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpmotree.TreeStructure'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='parent_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmotree.Project'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='parent_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmotree.Deliverable'),
        ),
    ]
