# Generated by Django 2.0.7 on 2018-10-03 08:56

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
