# Generated by Django 2.0.7 on 2018-08-28 12:41

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=4048)),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('nodetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vpmotree.NodeType')),
                ('parent_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmotree.Deliverable')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vpmotree.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
