# Generated by Django 2.0.7 on 2018-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestructure',
            name='node_type',
            field=models.CharField(default='Team', max_length=48),
        ),
    ]
