# Generated by Django 2.0.7 on 2018-11-30 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmotree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('content', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('impact', models.CharField(choices=[('1', 'Minor'), ('2', 'Moderate'), ('3', 'High')], default='1', max_length=1)),
                ('probability', models.CharField(choices=[('1', 'Low probability'), ('2', 'Medium probability'), ('3', 'High probability')], default='1', max_length=1)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='finish',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='treestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 30, 11, 41, 58, 637552, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treestructure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treestructure',
            name='model_name',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='treestructure',
            name='name',
            field=models.CharField(default='NewTreeName', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
