# Generated by Django 2.0.7 on 2018-10-04 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmotree', '0002_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpmotree.TreeStructure')),
            ],
        ),
    ]
