# Generated by Django 2.0.7 on 2018-10-02 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmotree', '0002_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('content', models.CharField(max_length=250)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('vpmotree.treestructure',),
        ),
    ]
