# Generated by Django 2.0.7 on 2018-12-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0002_auto_20181130_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='date_time',
        ),
    ]
