# Generated by Django 2.0.7 on 2018-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0002_treestructure_node_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('created_obj', 'Admin Level Permissions'), ('contribute_obj', 'Contributor Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='user_team',
            field=models.CharField(max_length=251, unique=True),
        ),
    ]
