# Generated by Django 2.0.7 on 2018-12-04 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmotree', '0003_auto_20181201_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='assignee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treestructure',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (0, 'Closed')], default=1),
        ),
    ]
