# Generated by Django 2.0.7 on 2018-10-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0003_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={'permissions': (('create_obj', 'Create Level Permissions'), ('delete_obj', 'Delete Level Permissions'), ('update_obj', 'Update Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('create_obj', 'Create Level Permissions'), ('delete_obj', 'Delete Level Permissions'), ('update_obj', 'Update Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('create_obj', 'Create Level Permissions'), ('delete_obj', 'Delete Level Permissions'), ('update_obj', 'Update Level Permissions'), ('read_obj', 'Read Level Permissions'))},
        ),
    ]
