# Generated by Django 2.0.7 on 2018-10-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0005_auto_20181007_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('create_obj', 'Create Level Permissions'), ('delete_obj', 'Delete Level Permissions'), ('update_obj', 'Update Level Permissions'), ('read_obj', 'Read Level Permissions'), ('edit_role', "Edit other user's role"))},
        ),
    ]
