# Generated by Django 2.0.7 on 2018-10-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0007_auto_20181010_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverable',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
