# Generated by Django 2.0.7 on 2018-10-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0008_auto_20181013_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
