# Generated by Django 2.0.7 on 2018-11-12 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpmotree', '0010_deliverable_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('treestructure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpmotree.TreeStructure')),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('severity', models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default='1', max_length=1)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('vpmotree.treestructure',),
        ),
    ]
