# Generated by Django 2.0.7 on 2018-11-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0011_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='node',
        ),
        migrations.AddField(
            model_name='treestructure',
            name='channel_sid',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
