# Generated by Django 2.0.7 on 2018-11-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpmotree', '0012_auto_20181121_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='node',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
