# Generated by Django 2.0.7 on 2018-11-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vpmotree', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('vpmoauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_node', to='vpmotree.TreeStructure'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(to='vpmoauth.UserRolePermission'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='favorite_nodes',
            field=models.ManyToManyField(blank=True, to='vpmotree.TreeStructure'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
    ]
