# Generated by Django 2.0.7 on 2018-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoauth', '0003_myuser_favorite_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
