# Generated by Django 2.0.7 on 2018-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpmoauth', '0004_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='twilio_sid',
            field=models.CharField(default='Radnom', max_length=34),
            preserve_default=False,
        ),
    ]
